// Mocks generated by Mockito 5.4.4 from annotations
// in relink/test/unit/providers/indonesia_tourism_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:relink/services/indonesia_tourism_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IndonesiaTourismService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIndonesiaTourismService extends _i1.Mock
    implements _i2.IndonesiaTourismService {
  MockIndonesiaTourismService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getProvinces() => (super.noSuchMethod(
        Invocation.method(
          #getProvinces,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getProvince(String? provinceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvince,
          [provinceId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<String>> getCitiesByProvince(String? provinceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCitiesByProvince,
          [provinceId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchProvinces(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProvinces,
          [query],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTourismCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTourismCategories,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getTourismCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTourismCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPopularDestinationsByProvince(
    String? provinceId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularDestinationsByProvince,
          [provinceId],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getFeaturedDestinations({
    String? category,
    String? province,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedDestinations,
          [],
          {
            #category: category,
            #province: province,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDestinationsByTourismCategory(
    String? categoryId, {
    String? province,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDestinationsByTourismCategory,
          [categoryId],
          {
            #province: province,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTravelRecommendations({
    required List<String>? interests,
    String? budget,
    int? days,
    String? startLocation,
    int? limit = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTravelRecommendations,
          [],
          {
            #interests: interests,
            #budget: budget,
            #days: days,
            #startLocation: startLocation,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getTourismStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTourismStatistics,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> validateProvinceCity(
    String? provinceId,
    String? cityName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateProvinceCity,
          [
            provinceId,
            cityName,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>?> getProvinceByCity(String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvinceByCity,
          [cityName],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
